// <auto-generated />
using FoodTronix.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace FoodTronix.Migrations
{
    [DbContext(typeof(FoodTronixContext))]
    [Migration("20180204192101_migrate-1")]
    partial class migrate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("FoodTronix.Models.Entities.Dish", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<string>("Image")
                        .IsRequired();

                    b.Property<int>("MealID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("MealID");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("DishID");

                    b.Property<int>("OrderGroupID");

                    b.HasKey("ID");

                    b.HasIndex("DishID");

                    b.HasIndex("OrderGroupID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.Meal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Meal");
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.OrderGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("OrderGroup");
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.Dish", b =>
                {
                    b.HasOne("FoodTronix.Models.Entities.Meal", "Meal")
                        .WithMany("Dishes")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.Item", b =>
                {
                    b.HasOne("FoodTronix.Models.Entities.Dish", "Dish")
                        .WithMany("Items")
                        .HasForeignKey("DishID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoodTronix.Models.Entities.OrderGroup", "OrderGroup")
                        .WithMany("Items")
                        .HasForeignKey("OrderGroupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FoodTronix.Models.Entities.OrderGroup", b =>
                {
                    b.HasOne("FoodTronix.Models.Entities.User", "User")
                        .WithMany("OrderGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
